site_name: MASDiff
theme:
  name: material

markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

nav:
  - 首页: index.md
  - 2026-5-25流程解析: step_analysis.md
  - 2026-6-7提升ρ: 2026-6-7提升ρ.md
  - 2026-6-16采样: 2026-6-16采样.md
  - 学习记录: 学习记录.md
  - 2026-7-3: 2026-7-3.md



